#!/usr/bin/env node
/* =====================================================================
   NextStopGuides — site builder (no npm packages needed)
   ---------------------------------------------------------------------
   Kullanım / Usage (nextstopguides-web klasöründe):
       node tools/build-guides.js

   Reads:  assets/js/config.js, assets/js/i18n.js,
           assets/data/guides.js, assets/data/packing.js, assets/js/catalog.js
   Writes: index.html
           guides/index.html
           guides/<slug>/index.html   (one SEO page per guide)
           packing-list/index.html
           sitemap.xml, robots.txt
   Also removes generated guide folders whose slug is no longer in the catalog.
   ===================================================================== */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const GEN_MARK = '<!-- GENERATED by tools/build-guides.js — do not edit this file by hand. Edit assets/js/i18n.js or assets/data/*.js, then run: node tools/build-guides.js -->';
const read = (f) => fs.readFileSync(path.join(ROOT, f), 'utf8');
const exists = (f) => fs.existsSync(path.join(ROOT, f));
function write(rel, content) {
  const full = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content, 'utf8');
  written.push(rel.replace(/\\/g, '/'));
}
const written = [];

/* ---------------------------- load data ---------------------------- */
const ctx = {};
ctx.window = ctx;
vm.createContext(ctx);
for (const f of ['assets/js/config.js', 'assets/js/i18n.js', 'assets/data/guides.js', 'assets/data/packing.js', 'assets/js/catalog.js']) {
  try { vm.runInContext(read(f), ctx, { filename: f }); }
  catch (e) { fail(`${f} okunamadı / could not be parsed:\n  ${e.message}\n  (Genelde eksik virgül, tırnak veya parantez.)`); }
}
const CFG = ctx.NSG_CONFIG, I18N = ctx.NSG_I18N, CAT = ctx.NSG_CATALOG, PACK = ctx.NSG_PACKING, R = ctx.NSG_CAT;
const SITE = String(CFG.site && CFG.site.url || '').replace(/\/+$/, '');
const LANGS = Object.keys(I18N.languages);
const EN = I18N.strings.en;
const GUIDES = CAT.guides;
const esc = R.esc;

function fail(msg) { console.error('\n✖ ' + msg + '\n'); process.exit(1); }

/* --------------------------- validation --------------------------- */
(function validate() {
  if (!/^https:\/\/[^/]+$/.test(SITE)) fail('config.js → site.url must look like https://example.com (no trailing slash).');
  const seen = new Set();
  GUIDES.forEach((g, i) => {
    const where = `guides.js → guide #${i + 1} (${g.slug || 'no slug'})`;
    if (!g.slug || !/^[a-z0-9]+(-[a-z0-9]+)*$/.test(g.slug)) fail(`${where}: slug sadece küçük harf, rakam ve tire içermeli / slug must be lowercase-with-dashes.`);
    if (seen.has(g.slug)) fail(`${where}: aynı slug iki kez kullanılmış / duplicate slug.`);
    seen.add(g.slug);
    if (!Number.isInteger(g.days) || g.days < 1) fail(`${where}: days bir sayı olmalı (örn. 7) / days must be a whole number.`);
    if (!g.destination) fail(`${where}: destination eksik / missing destination.`);
    if (!CAT.destinations[g.destination] && !g.destinationName) fail(`${where}: '${g.destination}' destinations listesinde yok. Listeye ekleyin ya da destinationName: { en: '...' } yazın.`);
    const en = g.text && g.text.en;
    if (!en || !en.title || !en.description) fail(`${where}: text.en.title ve text.en.description zorunlu / required.`);
    if (!R.isUrl(g.etsy)) fail(`${where}: etsy linki https:// ile başlamalı / etsy must be a full URL.`);
    if (!R.isUrl(g.image)) fail(`${where}: image linki https:// ile başlamalı / image must be a full URL.`);
  });
})();

/* ---------------------------- helpers ---------------------------- */
function T(key, n) {
  if (!(key in EN)) fail(`i18n.js → strings.en['${key}'] eksik / missing.`);
  return n === undefined ? EN[key] : String(EN[key]).replace(/\{n\}/g, n);
}
const stripTags = (s) => String(s).replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
const plain = (s) => stripTags(s).replace(/&amp;/g, '&').replace(/ /g, ' ');
/* element with translatable text: <tag attrs data-i18n="key">English</tag> */
function tx(tag, key, attrs) { return `<${tag}${attrs ? ' ' + attrs : ''} data-i18n="${key}">${T(key)}</${tag}>`; }
const abs = (p) => SITE + '/' + p.replace(/^\/+/, '');
const guideUrl = (g) => abs(`guides/${g.slug}/`);
const hasFile = (f) => exists(f);
const DEFAULT_OG = hasFile('assets/img/og-image.jpg')
  ? { url: abs('assets/img/og-image.jpg'), w: 1200, h: 630 }
  : { url: R.socialImage(GUIDES[0].image), w: 1200, h: 1200 };
const liveItems = R.liveItems();
const getPath = (obj, p) => p.split('.').reduce((o, k) => (o && o[k] !== undefined ? o[k] : undefined), obj);

function priceOffer(price, url) {
  if (R.isPlaceholder(price)) return null;
  const m = String(price).match(/([€$£₺¥])\s*([\d.,]+)|([\d.,]+)\s*(USD|EUR|GBP|TRY|€|\$|£|₺)/i);
  if (!m) return null;
  const sym = (m[1] || m[4] || '').toUpperCase();
  const map = { '$': 'USD', '€': 'EUR', '£': 'GBP', '₺': 'TRY', '¥': 'JPY', USD: 'USD', EUR: 'EUR', GBP: 'GBP', TRY: 'TRY' };
  let num = m[2] || m[3];
  if (num.includes(',') && !num.includes('.')) num = num.replace(',', '.');
  num = num.replace(/,/g, '');
  if (!map[sym] || isNaN(parseFloat(num))) return null;
  return { '@type': 'Offer', price: String(parseFloat(num)), priceCurrency: map[sym], availability: 'https://schema.org/InStock', url };
}

function productLD(g) {
  const en = R.guideText(g, 'en');
  const p = {
    '@type': 'Product',
    name: en.title,
    description: en.description,
    image: [R.largeImage(g.image)],
    url: guideUrl(g),
    sku: g.slug,
    category: 'Printable travel itinerary (PDF)',
    brand: { '@type': 'Brand', name: 'NextStopGuides' }
  };
  const offers = [];
  const etsyOffer = priceOffer(g.price, g.etsy);
  if (etsyOffer) offers.push(etsyOffer);
  const shopierOffer = R.isUrl(g.shopier) ? priceOffer(g.priceTRY, g.shopier) : null;
  if (shopierOffer) offers.push(shopierOffer);
  if (offers.length) p.offers = offers.length === 1 ? offers[0] : offers;
  return p;
}

function breadcrumbLD(items) {
  return {
    '@type': 'BreadcrumbList',
    itemListElement: items.map((it, i) => ({ '@type': 'ListItem', position: i + 1, name: it[0], item: it[1] }))
  };
}

function jsonLd(graph) {
  return '<script type="application/ld+json">\n' +
    JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }, null, 2).replace(/</g, '\\u003c') +
    '\n  </script>';
}

/* ------------------------------ <head> ------------------------------ */
function head(o) {
  const hreflang = LANGS.map((l) =>
    `  <link rel="alternate" hreflang="${l}" href="${o.url}${l === 'en' ? '' : '?lang=' + l}">`).join('\n');
  const ogAlt = LANGS.filter((l) => l !== 'en').map((l) => `  <meta property="og:locale:alternate" content="${I18N.ogLocale[l]}">`).join('\n');
  const img = o.image || DEFAULT_OG;
  const scripts = ['assets/js/config.js', 'assets/js/i18n.js', 'assets/data/guides.js']
    .concat(o.extraData || [], ['assets/js/catalog.js', 'assets/js/main.js'])
    .map((s) => `  <script src="${o.base}${s}" defer></script>`).join('\n');
  const htmlAttrs = [
    o.titleKey ? `data-title-key="${o.titleKey}"` : '',
    o.descKey ? `data-desc-key="${o.descKey}"` : ''
  ].filter(Boolean).join(' ');
  return `<!DOCTYPE html>
<html lang="en"${htmlAttrs ? ' ' + htmlAttrs : ''}>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script>document.documentElement.classList.add('js');</script>
  ${GEN_MARK}

  <title>${esc(plain(o.title))}</title>
  <meta name="description" content="${esc(plain(o.desc))}">
  <meta name="theme-color" content="#15625e">
  <meta name="robots" content="${o.noindex ? 'noindex, follow' : 'index, follow'}">
  <link rel="canonical" href="${o.url}">
${hreflang}
  <link rel="alternate" hreflang="x-default" href="${o.url}">

  <meta property="og:type" content="${o.ogType || 'website'}">
  <meta property="og:site_name" content="NextStopGuides">
  <meta property="og:title" content="${esc(plain(o.title))}">
  <meta property="og:description" content="${esc(plain(o.desc))}">
  <meta property="og:url" content="${o.url}">
  <meta property="og:image" content="${esc(img.url)}">
${img.w ? `  <meta property="og:image:width" content="${img.w}">\n  <meta property="og:image:height" content="${img.h}">\n` : ''}  <meta property="og:image:alt" content="${esc(plain(o.imageAlt || o.title))}">
  <meta property="og:locale" content="en_US">
${ogAlt}
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${esc(plain(o.title))}">
  <meta name="twitter:description" content="${esc(plain(o.desc))}">
  <meta name="twitter:image" content="${esc(img.url)}">

  <link rel="icon" href="${o.base}favicon.svg" type="image/svg+xml">
${hasFile('assets/img/apple-touch-icon.png') ? `  <link rel="apple-touch-icon" href="${o.base}assets/img/apple-touch-icon.png">\n` : ''}  <link rel="manifest" href="${o.base}site.webmanifest">

  <link rel="preconnect" href="https://cdn.tailwindcss.com">
  <link rel="preconnect" href="https://i.etsystatic.com">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700;800&display=swap">
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="${o.base}assets/js/tw-config.js"></script>
  <link rel="stylesheet" href="${o.base}assets/css/styles.css">

  ${jsonLd(o.ld)}

${scripts}
</head>`;
}

/* ------------------------------ header ------------------------------ */
function header(base, active, onIndex) {
  const href = {
    home: base || './',
    guides: onIndex ? '#guides' : base + 'guides/',
    essentials: base + '#essentials',
    packing: base + 'packing-list/',
    faq: base + '#faq',
    trivia: base + '#trivia'
  };
  const items = [['guides', 'nav.guides'], ['essentials', 'nav.essentials'], ['packing', 'nav.packing'], ['faq', 'nav.faq'], ['trivia', 'nav.trivia']];
  const cur = (k) => (k === active ? ' aria-current="page"' : '');
  const desk = items.map(([k, key]) =>
    `        <li><a class="whitespace-nowrap transition hover:text-ocean-700${k === active ? ' text-ocean-700' : ''}" href="${href[k]}"${cur(k)} data-i18n="${key}">${T(key)}</a></li>`).join('\n');
  const mob = items.map(([k, key]) =>
    `        <li><a class="block rounded-lg px-3 py-3 hover:bg-ink/5" href="${href[k]}"${cur(k)} data-i18n="${key}">${T(key)}</a></li>`).join('\n');
  return `
  <a href="#main" class="skip-link rounded-lg bg-ink px-4 py-2 text-sm font-semibold text-white" data-i18n="a11y.skip">${T('a11y.skip')}</a>

  <header id="site-header" class="sticky top-0 z-50 border-b border-ink/5 bg-sand-50/80 backdrop-blur">
    <nav class="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-3 sm:px-6" aria-label="Main">
      <a href="${href.home}" class="flex shrink-0 items-center gap-2 font-display text-lg font-extrabold tracking-tight text-ink" aria-label="NextStopGuides home">
        <img src="${base}favicon.svg" alt="" width="32" height="32" class="h-8 w-8">
        <span>NextStop<span class="text-ocean-700">Guides</span></span>
      </a>

      <ul class="hidden items-center gap-6 text-sm font-medium text-ink-soft lg:flex">
${desk}
      </ul>

      <div class="flex items-center gap-2">
        <div class="relative" data-lang-switcher>
          <button id="lang-btn" type="button" class="inline-flex items-center gap-1.5 rounded-full border border-ink/15 px-3 py-1.5 text-xs font-bold tracking-wide text-ink transition hover:border-ocean-600 hover:text-ocean-700" aria-haspopup="menu" aria-expanded="false" aria-controls="lang-menu" aria-label="Change language: English">
            <svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.5 2.7 3.8 5.7 3.8 9s-1.3 6.3-3.8 9c-2.5-2.7-3.8-5.7-3.8-9S9.5 5.7 12 3z"/></svg>
            <span data-lang-current>EN</span>
            <svg class="h-3 w-3" viewBox="0 0 12 12" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 4.5 6 7.5 9 4.5"/></svg>
          </button>
          <ul id="lang-menu" role="menu" aria-label="Language" hidden class="absolute right-0 top-full z-50 mt-2 w-44 rounded-2xl bg-white p-1.5 shadow-xl ring-1 ring-ink/10"></ul>
        </div>
        <a href="${href.guides}" class="hidden whitespace-nowrap rounded-full bg-coral-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-coral-700 sm:inline-block" data-i18n="nav.cta">${T('nav.cta')}</a>
        <button id="menu-btn" type="button" class="inline-flex h-10 w-10 items-center justify-center rounded-full text-ink transition hover:bg-ink/5 lg:hidden" aria-controls="mobile-menu" aria-expanded="false" aria-label="${T('nav.menu')}" data-i18n-attr="aria-label:nav.menu">
          <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg>
        </button>
      </div>
    </nav>

    <div id="mobile-menu" class="hidden border-t border-ink/5 bg-sand-50 lg:hidden">
      <ul class="mx-auto flex max-w-6xl flex-col px-4 py-3 text-base font-medium sm:px-6">
${mob}
        <li class="px-3 pt-3">
          <p id="lang-mobile-label" class="text-xs font-bold uppercase tracking-widest text-ink-soft" data-i18n="nav.language">${T('nav.language')}</p>
          <div id="lang-mobile" role="group" aria-labelledby="lang-mobile-label" class="mt-2 grid grid-cols-5 gap-2"></div>
        </li>
        <li class="pt-4"><a class="block rounded-full bg-coral-600 px-4 py-3 text-center font-semibold text-white" href="${href.guides}" data-i18n="nav.cta">${T('nav.cta')}</a></li>
      </ul>
    </div>
  </header>`;
}

/* ------------------------------ footer ------------------------------ */
function footer(base) {
  const social = [
    ['instagram', 'Instagram', '<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor"/>'],
    ['tiktok', 'TikTok', '<path d="M14 3v11.5a3.5 3.5 0 1 1-3.5-3.5M14 3c.5 2.5 2.5 4.5 5 5"/>'],
    ['youtube', 'YouTube', '<rect x="2.5" y="5.5" width="19" height="13" rx="4"/><path d="M10 9.5v5l4.5-2.5z" fill="currentColor"/>'],
    ['pinterest', 'Pinterest', '<circle cx="12" cy="12" r="9"/><path d="M11 8.5c3-1 5 .5 5 3s-2 4-3.5 3.5M12 11l-2.5 9.5"/>']
  ].map(([k, label, svg]) =>
    `          <a href="#" data-link="social.${k}" target="_blank" rel="noopener" class="flex h-10 w-10 items-center justify-center rounded-full bg-white text-ink ring-1 ring-ink/10 transition hover:text-coral-600" aria-label="${label}">
            <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${svg}</svg>
          </a>`).join('\n');
  const guideLinks = GUIDES.slice(0, 6).map((g) =>
    `          <li><a class="hover:text-ocean-700" href="${base}guides/${g.slug}/" data-guide-title="${g.slug}">${esc(R.guideText(g, 'en').title)}</a></li>`).join('\n');
  return `
  <footer class="border-t border-ink/10 bg-sand-100">
    <div class="mx-auto grid max-w-6xl gap-10 px-4 py-14 sm:px-6 md:grid-cols-4">
      <div class="md:col-span-2">
        <a href="${base || './'}" class="flex items-center gap-2 font-display text-lg font-extrabold">
          <img src="${base}favicon.svg" alt="" width="28" height="28" class="h-7 w-7">
          <span>NextStop<span class="text-ocean-700">Guides</span></span>
        </a>
        ${tx('p', 'footer.tagline', 'class="mt-3 max-w-sm text-sm text-ink-soft"')}
        <div class="mt-5 flex gap-3">
${social}
        </div>
      </div>
      <nav aria-label="Footer: itineraries">
        ${tx('h2', 'footer.guides', 'class="text-sm font-bold uppercase tracking-widest text-ink"')}
        <ul class="mt-4 space-y-2 text-sm text-ink-soft">
${guideLinks}
          <li><a class="font-semibold text-ocean-700 hover:text-ocean-900" href="${base}guides/" data-i18n="footer.allGuides">${T('footer.allGuides')}</a></li>
          <li><a class="hover:text-ocean-700" href="${base}packing-list/" data-i18n="footer.packing">${T('footer.packing')}</a></li>
        </ul>
      </nav>
      <nav aria-label="Footer: company">
        ${tx('h2', 'footer.company', 'class="text-sm font-bold uppercase tracking-widest text-ink"')}
        <ul class="mt-4 space-y-2 text-sm text-ink-soft">
          <li><a class="hover:text-ocean-700" href="#" data-link="shops.etsy" target="_blank" rel="noopener">Etsy</a></li>
          <li><a class="hover:text-ocean-700" href="#" data-link="shops.shopier" target="_blank" rel="noopener">Shopier</a></li>
          <li><a class="hover:text-ocean-700" href="#" data-link="contact.email" data-i18n="footer.contact">${T('footer.contact')}</a></li>
          <li><a class="hover:text-ocean-700" href="${base}privacy.html" data-i18n="footer.privacy">${T('footer.privacy')}</a></li>
        </ul>
      </nav>
    </div>
    <div class="border-t border-ink/10">
      <div class="mx-auto max-w-6xl space-y-2 px-4 py-6 text-xs text-ink-soft sm:px-6">
        ${tx('p', 'footer.disclosure')}
        <p>© <span data-year>${new Date().getFullYear()}</span> NextStopGuides. ${tx('span', 'footer.rights')}</p>
      </div>
    </div>
  </footer>
</body>
</html>
`;
}

/* ---- Airalo code box (config.js → affiliates.airaloCode) — only rendered when a code is set ---- */
function airaloCodeBox() {
  const code = getPath(CFG, 'affiliates.airaloCode');
  if (typeof code !== 'string' || R.isPlaceholder(code)) return '';
  const set = true;
  return `
            <div class="mt-4 rounded-2xl border-2 border-dashed border-ocean-300 bg-ocean-50 p-3" data-config-wrap="affiliates.airaloCode"${set ? '' : ' hidden'}>
              <div class="flex flex-wrap items-center justify-between gap-2">
                <p class="min-w-0 text-sm">${tx('span', 'ess.airalo.codeLabel', 'class="text-ink-soft"')} <code class="font-mono text-base font-bold tracking-wider text-ink" data-config-text>${set ? esc(code) : ''}</code></p>
                <button type="button" data-copy-config="affiliates.airaloCode" class="shrink-0 rounded-full bg-ocean-700 px-3 py-1.5 text-xs font-semibold text-white transition hover:bg-ocean-800">${tx('span', 'ess.airalo.copy')}</button>
              </div>
              ${tx('p', 'ess.airalo.codeHint', 'class="mt-1.5 text-xs text-ink-soft"')}
            </div>`;
}

/* ------------------------- catalog widget ------------------------- */
function catalogWidget(base) {
  const opts = [['featured', 'cat.sort.featured'], ['daysAsc', 'cat.sort.daysAsc'], ['daysDesc', 'cat.sort.daysDesc'], ['az', 'cat.sort.az']]
    .map(([v, key]) => `              <option value="${v}" data-i18n="${key}">${T(key)}</option>`).join('\n');
  const cards = GUIDES.map((g) => R.cardHTML(g, 'en', base)).join('\n') + '\n' + R.soonCardHTML('en', base);
  const count = GUIDES.length === 1 ? T('cat.countOne') : T('cat.countMany', GUIDES.length);
  return `
      <div data-catalog data-base="${base}" class="mt-12">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div class="flex flex-wrap gap-2" role="group" aria-label="${T('cat.filterLabel')}" data-i18n-attr="aria-label:cat.filterLabel" data-catalog-chips></div>
          <div class="flex flex-col gap-3 sm:flex-row">
            <div class="relative sm:w-72">
              ${tx('label', 'cat.searchLabel', 'for="cat-search" class="sr-only"')}
              <svg class="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-ink-soft" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>
              <input id="cat-search" type="search" autocomplete="off" data-catalog-search placeholder="${T('cat.searchPlaceholder')}" data-i18n-attr="placeholder:cat.searchPlaceholder" class="w-full rounded-full border border-ink/15 bg-white py-2.5 pl-10 pr-4 text-sm text-ink placeholder:text-ink-soft/70 focus:border-ocean-600 focus:outline-none focus:ring-2 focus:ring-ocean-200">
            </div>
            <div>
              ${tx('label', 'cat.sortLabel', 'for="cat-sort" class="sr-only"')}
              <select id="cat-sort" data-catalog-sort class="w-full rounded-full border border-ink/15 bg-white py-2.5 pl-4 pr-10 text-sm font-medium text-ink focus:border-ocean-600 focus:outline-none focus:ring-2 focus:ring-ocean-200 sm:w-auto">
${opts}
              </select>
            </div>
          </div>
        </div>
        <p data-catalog-count class="mt-4 text-sm text-ink-soft" aria-live="polite">${count}</p>
        <div data-catalog-grid class="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
${cards}
        </div>
      </div>`;
}

function breadcrumbNav(items) {
  const parts = items.map(([key, href, extra], i) => {
    const last = i === items.length - 1;
    if (last) return key.startsWith('raw:')
      ? `<li aria-current="page" class="font-medium text-ink"${extra || ''}>${esc(key.slice(4))}</li>`
      : `<li aria-current="page" class="font-medium text-ink" data-i18n="${key}">${T(key)}</li>`;
    return `<li><a class="transition hover:text-ocean-700" href="${href}" data-i18n="${key}">${T(key)}</a></li><li aria-hidden="true">/</li>`;
  }).join('');
  return `<nav aria-label="${T('gp.breadcrumb')}" data-i18n-attr="aria-label:gp.breadcrumb" class="text-sm text-ink-soft"><ol class="flex flex-wrap items-center gap-x-2 gap-y-1">${parts}</ol></nav>`;
}

/* ============================ PAGES ============================ */

/* ---------- index.html ---------- */
function buildIndex() {
  const base = '';
  const faqN = [1, 2, 3, 4, 5, 6];
  const sameAs = [CFG.shops.etsy, CFG.shops.shopier].concat(Object.values(CFG.social || {})).filter(R.isUrl);
  const ld = [
    Object.assign({ '@type': 'Organization', '@id': SITE + '/#organization', name: 'NextStopGuides', url: SITE + '/', logo: abs('favicon.svg'),
      description: plain(T('footer.tagline')) }, sameAs.length ? { sameAs } : {}),
    { '@type': 'WebSite', '@id': SITE + '/#website', name: 'NextStopGuides', url: SITE + '/', inLanguage: LANGS, publisher: { '@id': SITE + '/#organization' } },
    { '@type': 'ItemList', name: 'NextStopGuides printable travel itineraries',
      itemListElement: GUIDES.map((g, i) => ({ '@type': 'ListItem', position: i + 1, item: productLD(g) })) },
    { '@type': 'FAQPage', mainEntity: faqN.map((n) => ({ '@type': 'Question', name: plain(T('faq.q' + n)),
      acceptedAnswer: { '@type': 'Answer', text: plain(T('faq.a' + n)) } })) }
  ];

  const stat = (emoji, n) => `
            <div><dt class="sr-only" data-i18n="hero.s${n}label">${T('hero.s' + n + 'label')}</dt><dd class="text-2xl" aria-hidden="true">${emoji}</dd><dd class="mt-1 text-xs leading-snug text-ink-soft" data-i18n="hero.s${n}">${T('hero.s' + n)}</dd></div>`;

  const faq = faqN.map((n) => `
          <div class="faq-item py-2">
            <h3><button type="button" class="faq-btn flex w-full items-center justify-between gap-4 py-4 text-left font-semibold" aria-expanded="true" aria-controls="faq-a${n}" id="faq-q${n}"><span class="min-w-0" data-i18n="faq.q${n}">${T('faq.q' + n)}</span><span class="faq-icon flex h-7 w-7 shrink-0 items-center justify-center text-2xl font-light leading-none text-ocean-700" aria-hidden="true">+</span></button></h3>
            <div id="faq-a${n}" class="faq-panel pb-5 text-sm leading-relaxed text-ink-soft" role="region" aria-labelledby="faq-q${n}" data-i18n="faq.a${n}">${T('faq.a' + n)}</div>
          </div>`).join('');

  const why = [['🧭', 1], ['✅', 2], ['🔗', 3], ['📱', 4]].map(([e, n]) => `
          <div class="reveal">
            <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-sand-100 text-2xl" aria-hidden="true">${e}</div>
            ${tx('h3', `why.f${n}.title`, 'class="mt-4 font-display text-lg font-bold"')}
            ${tx('p', `why.f${n}.desc`, 'class="mt-2 text-sm leading-relaxed text-ink-soft"')}
          </div>`).join('');

  const testimonials = [1, 2, 3].map((n) => `
          <figure class="reveal rounded-3xl bg-white/5 p-7 ring-1 ring-white/10">
            <p class="text-coral-300" role="img" aria-label="${T('t.stars')}" data-i18n-attr="aria-label:t.stars">★★★★★</p>
            ${tx('blockquote', 't.q' + n, 'class="mt-4 text-sm leading-relaxed text-sand-100"')}
            ${tx('figcaption', 't.w' + n, 'class="mt-5 text-xs font-semibold text-ocean-200"')}
          </figure>`).join('');

  const partner = (o) => `
          <article${o.id ? ` id="${o.id}" data-deeplink` : ''} class="card-lift reveal flex scroll-mt-24 flex-col rounded-3xl bg-white p-7 shadow-sm ring-1 ring-ink/5">
            <div class="flex h-14 w-14 items-center justify-center rounded-2xl ${o.tone}">
              <svg class="h-7 w-7" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${o.icon}</svg>
            </div>
            <div class="mt-5 flex flex-wrap items-center gap-2">
              ${tx('p', o.k + '.kicker', 'class="text-xs font-bold uppercase tracking-widest text-ink-soft"')}
              <span data-when-missing="${o.link}" class="rounded-full bg-sand-200 px-2 py-0.5 text-[11px] font-bold text-ink"${R.isPlaceholder(getPath(CFG, o.link)) ? '' : ' hidden'} data-i18n="ess.soon">${T('ess.soon')}</span>
            </div>
            ${o.titleKey ? tx('h3', o.titleKey, 'class="mt-1 font-display text-xl font-bold"') : `<h3 class="mt-1 font-display text-xl font-bold">${o.title}</h3>`}
            ${tx('p', o.k + '.desc', 'class="mt-2 flex-1 text-sm leading-relaxed text-ink-soft"')}${o.extra || ''}
            <a href="#" data-link="${o.link}" target="_blank" rel="${o.rel || 'sponsored noopener'}" class="mt-6 inline-flex items-center justify-center gap-1.5 rounded-full bg-ocean-700 px-4 py-3 text-center text-sm font-semibold text-white transition hover:bg-ocean-800">
              ${tx('span', o.k + '.cta')} <span aria-hidden="true">↗</span>
            </a>
          </article>`;

  const html = head({
    base, url: SITE + '/', title: T('meta.title'), desc: T('meta.description'), ld,
    imageAlt: 'NextStopGuides printable travel itineraries'
  }) + `

<body class="bg-sand-50 font-sans text-ink antialiased">` + header(base, '', true) + `

  <main id="main">
    <!-- ============================ HERO ============================ -->
    <section id="top" class="hero-bg relative overflow-hidden">
      <div class="dot-grid pointer-events-none absolute inset-0 opacity-60" aria-hidden="true"></div>
      <div class="relative mx-auto grid max-w-6xl items-center gap-12 px-4 pb-20 pt-14 sm:px-6 md:pt-20 lg:grid-cols-2 lg:pb-28">
        <div>
          <p class="inline-flex items-center gap-2 rounded-full bg-ocean-100 px-3 py-1 text-xs font-semibold text-ocean-800">
            <span aria-hidden="true">🗾</span> ${tx('span', 'hero.badge')}
          </p>
          ${tx('h1', 'hero.title', 'class="mt-5 font-display text-4xl font-extrabold leading-[1.1] tracking-tight text-ink sm:text-5xl lg:text-6xl"')}
          ${tx('p', 'hero.subtitle', 'class="mt-5 max-w-xl text-lg leading-relaxed text-ink-soft"')}
          <div class="mt-8 flex flex-col gap-3 sm:flex-row">
            <a href="#guides" class="inline-flex items-center justify-center gap-2 rounded-full bg-coral-600 px-7 py-3.5 text-base font-semibold text-white shadow-lg shadow-coral-600/25 transition hover:-translate-y-0.5 hover:bg-coral-700">
              ${tx('span', 'hero.cta1')} <span aria-hidden="true">→</span>
            </a>
            ${tx('a', 'hero.cta2', 'href="#essentials" class="inline-flex items-center justify-center rounded-full border border-ink/15 bg-white px-7 py-3.5 text-base font-semibold text-ink transition hover:border-ocean-600 hover:text-ocean-700"')}
          </div>
          <dl class="mt-10 grid max-w-lg grid-cols-3 gap-4">${stat('🗓️', 1)}${stat('🖨️', 2)}${stat('✅', 3)}
          </dl>
        </div>

        <!-- Decorative postcards (no images required) -->
        <div class="relative mx-auto h-[360px] w-full max-w-[420px] sm:h-[420px]" aria-hidden="true">
          <div class="float absolute left-0 top-6 w-[62%] rounded-3xl bg-white p-3 shadow-xl" style="--r:-6deg">
            <div class="flex h-40 items-end rounded-2xl bg-gradient-to-br from-ocean-400 via-ocean-600 to-ocean-900 p-4 sm:h-48"><span class="text-5xl">🗼</span></div>
            ${tx('p', 'hero.c1', 'class="px-1 pt-3 font-display text-sm font-bold"')}
            ${tx('p', 'hero.c1meta', 'class="px-1 text-xs text-ink-soft"')}
          </div>
          <div class="float float-delay absolute right-0 top-0 w-[52%] rounded-3xl bg-white p-3 shadow-xl" style="--r:5deg">
            <div class="flex h-32 items-end rounded-2xl bg-gradient-to-br from-coral-300 via-coral-500 to-coral-800 p-4 sm:h-36"><span class="text-4xl">⛩️</span></div>
            ${tx('p', 'hero.c2', 'class="px-1 pt-3 font-display text-sm font-bold"')}
          </div>
          <div class="float absolute bottom-0 right-6 w-[58%] rounded-3xl bg-white p-3 shadow-xl" style="--r:3deg">
            <div class="flex h-32 items-end rounded-2xl bg-gradient-to-br from-sky-300 via-sky-500 to-ocean-700 p-4 sm:h-36"><span class="text-4xl">🏯</span></div>
            ${tx('p', 'hero.c3', 'class="px-1 pt-3 font-display text-sm font-bold"')}
          </div>
          <div class="absolute bottom-10 left-2 flex items-center gap-2 rounded-2xl bg-ink px-4 py-3 text-white shadow-xl">
            <span class="text-xl">📍</span>
            ${tx('span', 'hero.pin', 'class="text-xs font-semibold leading-tight"')}
          </div>
        </div>
      </div>
      <svg class="absolute bottom-0 left-0 block h-10 w-full text-white sm:h-14" viewBox="0 0 1440 80" preserveAspectRatio="none" aria-hidden="true"><path fill="currentColor" d="M0 48c160 24 320 32 480 20S800 16 960 16s320 28 480 40v24H0z"/></svg>
    </section>

    <!-- ============================ ITINERARY CATALOG ============================ -->
    <section id="guides" class="bg-white py-20 sm:py-24" aria-labelledby="guides-title">
      <div class="mx-auto max-w-6xl px-4 sm:px-6">
        <div class="mx-auto max-w-2xl text-center">
          ${tx('p', 'guides.eyebrow', 'class="text-sm font-bold uppercase tracking-widest text-coral-600"')}
          ${tx('h2', 'guides.title', 'id="guides-title" class="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl"')}
          ${tx('p', 'guides.subtitle', 'class="mt-4 text-ink-soft"')}
        </div>
${catalogWidget(base)}
        <div class="mt-12 flex flex-col items-center gap-4 text-center">
          <a href="guides/" class="inline-flex items-center gap-2 rounded-full border border-ink/15 bg-white px-6 py-3 text-sm font-semibold text-ink transition hover:border-ocean-600 hover:text-ocean-700">${tx('span', 'guides.viewAll')} <span aria-hidden="true">→</span></a>
          <p class="text-sm text-ink-soft">
            ${tx('span', 'guides.shopnote')}
            <a href="#" data-link="shops.etsy" target="_blank" rel="noopener" class="font-semibold text-ocean-700 underline underline-offset-4 hover:text-ocean-900" data-i18n="guides.etsyshop">${T('guides.etsyshop')}</a>
            ·
            <a href="#" data-link="shops.shopier" target="_blank" rel="noopener" class="font-semibold text-ocean-700 underline underline-offset-4 hover:text-ocean-900" data-i18n="guides.shopiershop">${T('guides.shopiershop')}</a>
          </p>
        </div>
      </div>
    </section>

    <!-- ============================ TRAVEL ESSENTIALS / PARTNERS ============================ -->
    <section id="essentials" class="bg-sand-100 py-20 sm:py-24" aria-labelledby="essentials-title">
      <div class="mx-auto max-w-6xl px-4 sm:px-6">
        <div class="reveal mx-auto max-w-2xl text-center">
          ${tx('p', 'ess.eyebrow', 'class="text-sm font-bold uppercase tracking-widest text-coral-600"')}
          ${tx('h2', 'ess.title', 'id="essentials-title" class="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl"')}
          ${tx('p', 'ess.subtitle', 'class="mt-4 text-ink-soft"')}
        </div>
        <div class="mt-14 grid gap-6 sm:grid-cols-2 xl:grid-cols-4">${partner({
          k: 'ess.airalo', id: 'airalo', title: 'Airalo', link: 'affiliates.airalo', tone: 'bg-ocean-100 text-ocean-700',
          extra: airaloCodeBox(),
          icon: '<path d="M7 3h7l4 4v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z"/><rect x="9" y="10" width="6" height="7" rx="1"/><path d="M12 10v7M9 13.5h6"/>'
        })}${partner({
          k: 'ess.klook', title: 'Klook', link: 'affiliates.klook', tone: 'bg-coral-100 text-coral-700',
          icon: '<path d="M3 8a2 2 0 0 0 2-2h14a2 2 0 0 0 2 2v2a2 2 0 0 0 0 4v2a2 2 0 0 0-2 2H5a2 2 0 0 0-2-2v-2a2 2 0 0 0 0-4z"/><path d="M14 6v12" stroke-dasharray="2 2"/>'
        })}${partner({
          k: 'ess.wp', title: 'Welcome Pickups', link: 'affiliates.welcomepickups', tone: 'bg-sand-200 text-ink',
          icon: '<path d="M3 13l2-5a2 2 0 0 1 1.9-1.3h10.2A2 2 0 0 1 19 8l2 5v4a1 1 0 0 1-1 1h-1M3 13v4a1 1 0 0 0 1 1h1M3 13h18"/><circle cx="7.5" cy="17.5" r="1.5"/><circle cx="16.5" cy="17.5" r="1.5"/>'
        })}${partner({
          k: 'ess.hotels', titleKey: 'ess.hotels.title', link: 'affiliates.hotels', tone: 'bg-sky-100 text-sky-800',
          icon: '<path d="M3 18V8M3 14h18v4M21 18v-4a3 3 0 0 0-3-3h-7v3"/><circle cx="7" cy="11" r="2"/>',
          extra: `
            <p class="mt-3 text-xs text-ink-soft" data-config-wrap="partners.hotelsProvider" hidden>${tx('span', 'ess.hotels.via')} <span class="font-semibold text-ink" data-config-text></span></p>`
        })}
        </div>
        <p class="mt-8 text-center">
          <a href="packing-list/" class="inline-flex items-center gap-2 text-sm font-semibold text-ocean-700 underline-offset-4 hover:underline"><span aria-hidden="true">🧳</span> ${tx('span', 'ess.packing')} <span aria-hidden="true">→</span></a>
        </p>
        ${tx('p', 'ess.disclosure', 'class="mx-auto mt-6 max-w-2xl text-center text-xs text-ink-soft"')}
      </div>
    </section>

    <!-- ============================ WHY NEXTSTOPGUIDES ============================ -->
    <section id="why" class="bg-white py-20 sm:py-24" aria-labelledby="why-title">
      <div class="mx-auto max-w-6xl px-4 sm:px-6">
        <div class="reveal mx-auto max-w-2xl text-center">
          ${tx('p', 'why.eyebrow', 'class="text-sm font-bold uppercase tracking-widest text-coral-600"')}
          ${tx('h2', 'why.title', 'id="why-title" class="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl"')}
        </div>
        <div class="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">${why}
        </div>
      </div>
    </section>

    <!-- ============================ TESTIMONIALS (EXAMPLES) ============================ -->
    <section id="testimonials" class="bg-ocean-900 py-20 text-white sm:py-24" aria-labelledby="testimonials-title">
      <div class="mx-auto max-w-6xl px-4 sm:px-6">
        <div class="reveal mx-auto max-w-2xl text-center">
          ${tx('p', 't.eyebrow', 'class="text-sm font-bold uppercase tracking-widest text-coral-300"')}
          ${tx('h2', 't.title', 'id="testimonials-title" class="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl"')}
          ${tx('p', 't.note', 'class="mt-4 inline-block rounded-full bg-white/10 px-4 py-1.5 text-xs font-semibold text-sand-100"')}
        </div>
        <div class="mt-12 grid gap-6 md:grid-cols-3">${testimonials}
        </div>
      </div>
    </section>

    <!-- ============================ NEWSLETTER ============================ -->
    <section id="newsletter" class="bg-white py-20 sm:py-24" aria-labelledby="newsletter-title">
      <div class="mx-auto max-w-6xl px-4 sm:px-6">
        <div class="reveal relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-coral-600 to-coral-800 px-6 py-12 text-white sm:px-12 sm:py-16">
          <div class="pointer-events-none absolute -right-16 -top-16 h-56 w-56 rounded-full bg-white/10" aria-hidden="true"></div>
          <div class="pointer-events-none absolute -bottom-20 -left-10 h-48 w-48 rounded-full bg-white/10" aria-hidden="true"></div>
          <div class="relative grid items-center gap-8 lg:grid-cols-2">
            <div>
              ${tx('h2', 'nl.title', 'id="newsletter-title" class="font-display text-3xl font-extrabold tracking-tight sm:text-4xl"')}
              ${tx('p', 'nl.subtitle', 'class="mt-3 text-coral-50"')}
            </div>
            <!-- The real form address is set in assets/js/config.js → newsletter.action -->
            <form id="newsletter-form" class="w-full" action="#" method="post" novalidate>
              ${tx('label', 'nl.label', 'for="nl-email" class="sr-only"')}
              <div class="flex flex-col gap-3 sm:flex-row">
                <input id="nl-email" name="email" type="email" autocomplete="email" required placeholder="${T('nl.placeholder')}" data-i18n-attr="placeholder:nl.placeholder" class="min-w-0 flex-1 rounded-full border-0 bg-white px-5 py-3.5 text-ink placeholder:text-ink-soft/70 focus:outline-none focus:ring-4 focus:ring-white/40">
                ${tx('button', 'nl.button', 'type="submit" class="rounded-full bg-ink px-6 py-3.5 font-semibold text-white transition hover:bg-ink/85"')}
              </div>
              <p id="nl-status" class="mt-3 min-h-[1.25rem] text-sm font-medium text-white" role="status" aria-live="polite"></p>
              ${tx('p', 'nl.privacy', 'class="mt-1 text-xs text-coral-50"')}
            </form>
          </div>
        </div>
      </div>
    </section>

    <!-- ============================ FAQ ============================ -->
    <section id="faq" class="bg-sand-100 py-20 sm:py-24" aria-labelledby="faq-title">
      <div class="mx-auto max-w-3xl px-4 sm:px-6">
        <div class="reveal text-center">
          ${tx('p', 'faq.eyebrow', 'class="text-sm font-bold uppercase tracking-widest text-coral-600"')}
          ${tx('h2', 'faq.title', 'id="faq-title" class="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl"')}
        </div>
        <div class="reveal mt-12 divide-y divide-ink/10 rounded-3xl bg-white px-5 shadow-sm ring-1 ring-ink/5 sm:px-8">${faq}
        </div>
      </div>
    </section>

    <!-- ============================ TRIVIA GAME TEASER ============================ -->
    <section id="trivia" class="bg-white py-20 sm:py-24" aria-labelledby="trivia-title">
      <div class="mx-auto max-w-6xl px-4 sm:px-6">
        <div class="reveal grid items-center gap-10 overflow-hidden rounded-[2rem] bg-ink px-6 py-12 text-white sm:px-12 lg:grid-cols-2">
          <div>
            ${tx('span', 'trivia.badge', 'class="inline-flex items-center gap-2 rounded-full bg-coral-600 px-3 py-1 text-xs font-bold uppercase tracking-wider"')}
            ${tx('h2', 'trivia.title', 'id="trivia-title" class="mt-5 font-display text-3xl font-extrabold tracking-tight sm:text-4xl"')}
            ${tx('p', 'trivia.desc', 'class="mt-4 leading-relaxed text-sand-200"')}
            <ul class="mt-6 space-y-2 text-sm text-sand-100">
              <li class="flex gap-2"><span aria-hidden="true">🌍</span>${tx('span', 'trivia.f1')}</li>
              <li class="flex gap-2"><span aria-hidden="true">🏆</span>${tx('span', 'trivia.f2')}</li>
              <li class="flex gap-2"><span aria-hidden="true">🎁</span>${tx('span', 'trivia.f3')}</li>
            </ul>
            <a href="#newsletter" class="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 font-semibold text-ink transition hover:bg-sand-200">
              ${tx('span', 'trivia.cta')} <span aria-hidden="true">🔔</span>
            </a>
          </div>
          <div class="mx-auto w-full max-w-sm" aria-hidden="true">
            <div class="rounded-3xl bg-white/5 p-6 ring-1 ring-white/10">
              ${tx('p', 'trivia.qnum', 'class="text-xs font-semibold uppercase tracking-wider text-coral-300"')}
              ${tx('p', 'trivia.q', 'class="mt-3 font-display text-lg font-bold"')}
              <div class="mt-5 grid gap-2 text-sm">
                ${tx('div', 'trivia.a1', 'class="rounded-xl bg-white/10 px-4 py-3"')}
                ${tx('div', 'trivia.a2', 'class="rounded-xl bg-ocean-600 px-4 py-3 font-semibold"')}
                ${tx('div', 'trivia.a3', 'class="rounded-xl bg-white/10 px-4 py-3"')}
                ${tx('div', 'trivia.a4', 'class="rounded-xl bg-white/10 px-4 py-3"')}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
` + footer(base);
  write('index.html', html);
}

/* ---------- guides/index.html ---------- */
function buildGuidesIndex() {
  const base = '../';
  const url = abs('guides/');
  const ld = [
    { '@type': 'CollectionPage', name: plain(T('meta.guides.title')), url, description: plain(T('meta.guides.description')), isPartOf: { '@id': SITE + '/#website' } },
    { '@type': 'ItemList', name: 'NextStopGuides printable travel itineraries',
      itemListElement: GUIDES.map((g, i) => ({ '@type': 'ListItem', position: i + 1, url: guideUrl(g), name: R.guideText(g, 'en').title })) },
    breadcrumbLD([[plain(T('nav.home')), SITE + '/'], [plain(T('nav.guides')), url]])
  ];
  const html = head({ base, url, title: T('meta.guides.title'), desc: T('meta.guides.description'), ld,
    titleKey: 'meta.guides.title', descKey: 'meta.guides.description' }) + `

<body class="bg-sand-50 font-sans text-ink antialiased">` + header(base, 'guides', false) + `

  <main id="main">
    <section class="hero-bg">
      <div class="mx-auto max-w-6xl px-4 pb-10 pt-8 sm:px-6">
        ${breadcrumbNav([['nav.home', base], ['nav.guides']])}
        <div class="mt-8 max-w-2xl">
          ${tx('p', 'gi.eyebrow', 'class="text-sm font-bold uppercase tracking-widest text-coral-600"')}
          ${tx('h1', 'gi.title', 'class="mt-3 font-display text-4xl font-extrabold tracking-tight sm:text-5xl"')}
          ${tx('p', 'gi.subtitle', 'class="mt-4 text-lg text-ink-soft"')}
        </div>
      </div>
    </section>
    <section class="bg-white pb-20 pt-2 sm:pb-24">
      <div class="mx-auto max-w-6xl px-4 sm:px-6">
${catalogWidget(base)}
      </div>
    </section>
${essentialsBand(base)}
  </main>
` + footer(base);
  write('guides/index.html', html);
}

function essentialsBand(base) {
  return `
    <section class="py-16" aria-labelledby="ess-band-title">
      <div class="mx-auto max-w-6xl px-4 sm:px-6">
        <div class="flex flex-col items-start gap-6 rounded-[2rem] bg-ocean-900 px-6 py-10 text-white sm:px-10 md:flex-row md:items-center md:justify-between">
          <div>
            ${tx('h2', 'gp.essTitle', 'id="ess-band-title" class="font-display text-2xl font-extrabold sm:text-3xl"')}
            ${tx('p', 'gp.essDesc', 'class="mt-2 text-ocean-100"')}
          </div>
          <div class="flex flex-col gap-3 sm:flex-row">
            <a href="${base}#essentials" class="inline-flex items-center justify-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-semibold text-ink transition hover:bg-sand-200">${tx('span', 'gp.essCta')} <span aria-hidden="true">→</span></a>
            <a href="${base}packing-list/" class="inline-flex items-center justify-center gap-2 rounded-full border border-white/30 px-6 py-3 text-sm font-semibold text-white transition hover:bg-white/10"><span aria-hidden="true">🧳</span> ${tx('span', 'nav.packing')}</a>
          </div>
        </div>
      </div>
    </section>`;
}

/* ---------- guides/<slug>/index.html ---------- */
function buildGuidePage(g) {
  const base = '../../';
  const url = guideUrl(g);
  const en = R.guideText(g, 'en');
  const price = R.isPlaceholder(g.price) ? '' : g.price;
  const img = R.largeImage(g.image);
  const social = R.socialImage(g.image);
  const etsyKey = price ? 'card.buyEtsy' : 'card.viewEtsy';
  const ld = [
    productLD(g),
    breadcrumbLD([[plain(T('nav.home')), SITE + '/'], [plain(T('nav.guides')), abs('guides/')], [en.title, url]])
  ];
  const related = R.relatedFor(g.slug, 3);
  const inside = [1, 2, 3, 4, 5, 6].map((n) =>
    `              <li class="flex gap-3"><span class="mt-0.5 text-coral-600" aria-hidden="true">●</span>${tx('span', 'gp.inside' + n)}</li>`).join('\n');
  const highlights = en.highlights.map((h) =>
    `<li class="flex gap-3"><span class="mt-0.5 text-ocean-600" aria-hidden="true">✓</span><span>${esc(h)}</span></li>`).join('');

  const html = head({
    base, url, title: `${en.title} — ${T('gp.titleSuffix')}`, desc: en.description, ld, ogType: 'product',
    image: social !== g.image ? { url: social, w: 1200, h: 1200 } : { url: g.image }, imageAlt: en.title,
    titleKey: 'none', descKey: 'none'
  }) + `

<body class="bg-sand-50 font-sans text-ink antialiased" data-guide="${g.slug}">` + header(base, 'guides', false) + `

  <main id="main">
    <div class="mx-auto max-w-6xl px-4 pt-6 sm:px-6">
      ${breadcrumbNav([['nav.home', base], ['nav.guides', '../'], ['raw:' + en.title, null, ' data-guide-field="title"']])}
    </div>

    <section class="mx-auto grid max-w-6xl gap-10 px-4 pb-16 pt-8 sm:px-6 lg:grid-cols-2 lg:items-start">
      <div class="overflow-hidden rounded-3xl bg-sand-100 shadow-xl ring-1 ring-ink/5">
        <img src="${esc(img)}" alt="${esc(en.title)}" data-guide-field="image-alt" width="794" height="794" fetchpriority="high" class="h-auto w-full">
      </div>
      <div>
        <div class="flex flex-wrap items-center gap-2 text-xs font-semibold">
          <span class="rounded-full bg-ocean-100 px-3 py-1 text-ocean-800" data-guide-field="dest">${esc(R.destName(g, 'en'))}</span>
          <span class="rounded-full bg-white px-3 py-1 text-ink ring-1 ring-ink/10" data-guide-field="days">${esc(T('card.days', g.days))}</span>
        </div>
        <h1 class="mt-4 font-display text-3xl font-extrabold leading-tight tracking-tight sm:text-4xl lg:text-5xl" data-guide-field="title">${esc(en.title)}</h1>
        <p class="mt-4 text-lg leading-relaxed text-ink-soft" data-guide-field="description">${esc(en.description)}</p>
        <p class="mt-5 text-sm text-ink-soft">${tx('span', 'gp.cities', 'class="font-semibold text-ink"')} ${esc((g.cities || []).join(' · '))}</p>
${price ? `        <p class="mt-6 font-display text-4xl font-extrabold">${esc(price)}</p>\n` : ''}        <div class="mt-7 flex flex-col gap-3 sm:flex-row sm:flex-wrap">
          <a href="${esc(g.etsy)}" target="_blank" rel="noopener" class="inline-flex items-center justify-center gap-2 rounded-full bg-coral-600 sm:whitespace-nowrap px-8 py-4 text-base font-semibold text-white shadow-lg shadow-coral-600/25 transition hover:-translate-y-0.5 hover:bg-coral-700">${tx('span', etsyKey)} <span aria-hidden="true">↗</span></a>
${R.isUrl(g.shopier) ? `          <a href="${esc(g.shopier)}" target="_blank" rel="noopener" class="inline-flex items-center justify-center gap-2 rounded-full border-2 border-ocean-700 sm:whitespace-nowrap px-7 py-3.5 text-base font-semibold text-ocean-700 transition hover:bg-ocean-700 hover:text-white">${tx('span', 'card.shopier')}${R.isPlaceholder(g.priceTRY) ? '' : ' <span class="whitespace-nowrap">· ' + esc(g.priceTRY) + '</span>'} <span aria-hidden="true">↗</span></a>\n` : ''}        </div>
        ${tx('p', 'gp.edition', 'class="mt-4 text-xs text-ink-soft"')}
      </div>
    </section>

    <section class="bg-white py-16 sm:py-20">
      <div class="mx-auto grid max-w-6xl gap-10 px-4 sm:px-6 md:grid-cols-2">
        <div>
          ${tx('h2', 'gp.highlights', 'class="font-display text-2xl font-extrabold sm:text-3xl"')}
          <ul class="mt-6 space-y-3 text-ink-soft" data-guide-field="highlights">${highlights}</ul>
        </div>
        <div class="rounded-3xl bg-sand-100 p-6 sm:p-8">
          ${tx('h2', 'gp.inside', 'class="font-display text-2xl font-extrabold"')}
          <ul class="mt-6 space-y-3 text-sm text-ink-soft">
${inside}
          </ul>
        </div>
      </div>
    </section>
${essentialsBand(base)}
${related.length ? `
    <section class="bg-white py-16 sm:py-20" aria-labelledby="related-title">
      <div class="mx-auto max-w-6xl px-4 sm:px-6">
        <div class="flex flex-wrap items-end justify-between gap-4">
          ${tx('h2', 'gp.related', 'id="related-title" class="font-display text-2xl font-extrabold sm:text-3xl"')}
          ${tx('a', 'gp.back', 'href="../" class="text-sm font-semibold text-ocean-700 underline-offset-4 hover:underline"')}
        </div>
        <div class="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3" data-related data-base="${base}">
${related.map((r) => R.cardHTML(r, 'en', base)).join('\n')}
        </div>
      </div>
    </section>` : ''}
  </main>
` + footer(base);
  write(`guides/${g.slug}/index.html`, html);
}

/* ---------- packing-list/index.html ---------- */
function buildPacking() {
  const base = '../';
  const url = abs('packing-list/');
  const ld = [breadcrumbLD([[plain(T('nav.home')), SITE + '/'], [plain(T('nav.packing')), url]])];
  const html = head({ base, url, title: T('meta.packing.title'), desc: T('meta.packing.description'), ld,
    titleKey: 'meta.packing.title', descKey: 'meta.packing.description', extraData: ['assets/data/packing.js'],
    noindex: liveItems.length === 0 }) + `

<body class="bg-sand-50 font-sans text-ink antialiased">` + header(base, 'packing', false) + `

  <main id="main">
    <section class="hero-bg">
      <div class="mx-auto max-w-4xl px-4 pb-10 pt-8 sm:px-6">
        ${breadcrumbNav([['nav.home', base], ['nav.packing']])}
        <div class="mt-8">
          ${tx('p', 'pk.eyebrow', 'class="text-sm font-bold uppercase tracking-widest text-coral-600"')}
          ${tx('h1', 'pk.title', 'class="mt-3 font-display text-4xl font-extrabold tracking-tight sm:text-5xl"')}
          ${tx('p', 'pk.intro', 'class="mt-4 text-lg text-ink-soft"')}
          ${tx('p', 'pk.disclosure', 'class="mt-6 rounded-2xl bg-white/80 px-4 py-3 text-sm font-medium text-ink ring-1 ring-ink/10"')}
        </div>
      </div>
    </section>
    <section class="pb-16 pt-6">
      <div class="mx-auto max-w-4xl px-4 sm:px-6">
        <div data-packing>
${R.packingHTML('en')}
        </div>
        <p class="mt-12 text-center">
          <a href="../guides/" class="inline-flex items-center gap-2 rounded-full bg-coral-600 px-6 py-3 text-sm font-semibold text-white transition hover:bg-coral-700">${tx('span', 'pk.more')} <span aria-hidden="true">→</span></a>
        </p>
      </div>
    </section>
  </main>
` + footer(base);
  write('packing-list/index.html', html);
}

/* ---------- sitemap.xml + robots.txt ---------- */
function buildSitemap() {
  const today = new Date().toISOString().slice(0, 10);
  const pages = [
    { loc: SITE + '/', pri: '1.0', freq: 'weekly' },
    { loc: abs('guides/'), pri: '0.9', freq: 'weekly' }
  ].concat(GUIDES.map((g) => ({ loc: guideUrl(g), pri: '0.8', freq: 'monthly' })));
  if (liveItems.length) pages.push({ loc: abs('packing-list/'), pri: '0.5', freq: 'monthly' });

  let out = `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/build-guides.js (node tools/build-guides.js). Domain comes from assets/js/config.js → site.url -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
`;
  pages.forEach((p) => {
    const alts = LANGS.map((l) => `    <xhtml:link rel="alternate" hreflang="${l}" href="${p.loc}${l === 'en' ? '' : '?lang=' + l}"/>`).join('\n')
      + `\n    <xhtml:link rel="alternate" hreflang="x-default" href="${p.loc}"/>`;
    LANGS.forEach((l) => {
      out += `  <url>\n    <loc>${p.loc}${l === 'en' ? '' : '?lang=' + l}</loc>\n${alts}\n    <lastmod>${today}</lastmod>\n    <changefreq>${p.freq}</changefreq>\n    <priority>${l === 'en' ? p.pri : (parseFloat(p.pri) - 0.1).toFixed(1)}</priority>\n  </url>\n`;
    });
  });
  out += `  <url>\n    <loc>${abs('privacy.html')}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>yearly</changefreq>\n    <priority>0.3</priority>\n  </url>\n</urlset>\n`;
  write('sitemap.xml', out);

  write('robots.txt', `# NextStopGuides — robots.txt (generated by tools/build-guides.js)
User-agent: *
Allow: /
Disallow: /404.html
Disallow: /tools/

Sitemap: ${abs('sitemap.xml')}
`);
}

/* ---------- remove pages of deleted guides ---------- */
function cleanStale() {
  const dir = path.join(ROOT, 'guides');
  if (!fs.existsSync(dir)) return [];
  const removed = [];
  const slugs = new Set(GUIDES.map((g) => g.slug));
  fs.readdirSync(dir, { withFileTypes: true }).forEach((d) => {
    if (!d.isDirectory() || slugs.has(d.name)) return;
    const f = path.join(dir, d.name, 'index.html');
    if (fs.existsSync(f) && fs.readFileSync(f, 'utf8').includes('GENERATED by tools/build-guides.js')) {
      fs.rmSync(path.join(dir, d.name), { recursive: true });
      removed.push('guides/' + d.name + '/');
    }
  });
  return removed;
}

/* ---------- cache busting ----------
   The domain's browser cache keeps JS/CSS for hours, so a returning visitor
   could mix fresh HTML with stale scripts. Every local .js/.css reference in
   every page gets ?v=<content hash>, which changes only when the file does. */
function stampAssets() {
  const crypto = require('crypto');
  const hash = (rel) => {
    const f = path.join(ROOT, rel);
    return fs.existsSync(f) ? crypto.createHash('md5').update(fs.readFileSync(f)).digest('hex').slice(0, 8) : null;
  };
  const pages = ['index.html', 'privacy.html', '404.html', 'guides/index.html', 'packing-list/index.html',
    ...GUIDES.map((g) => `guides/${g.slug}/index.html`)];
  pages.forEach((p) => {
    const file = path.join(ROOT, p);
    if (!fs.existsSync(file)) return;
    const html = fs.readFileSync(file, 'utf8');
    const out = html.replace(/((?:src|href)=")((?:\.\.\/|\/)*)(assets\/[\w./-]+\.(?:js|css))(?:\?v=\w+)?"/g,
      (m, attr, prefix, rel) => { const v = hash(rel); return v ? `${attr}${prefix}${rel}?v=${v}"` : m; });
    if (out !== html) fs.writeFileSync(file, out);
  });
}

/* ------------------------------ run ------------------------------ */
const removed = cleanStale();
buildIndex();
buildGuidesIndex();
GUIDES.forEach(buildGuidePage);
buildPacking();
buildSitemap();
stampAssets();

console.log(`\n✔ NextStopGuides build tamam / done — ${GUIDES.length} rehber / guides, ${liveItems.length} Amazon ürünü / packing items live\n`);
written.forEach((f) => console.log('  ✎ ' + f));
removed.forEach((f) => console.log('  🗑 ' + f + ' (katalogda yok / no longer in catalog)'));
if (!liveItems.length) console.log('\n  ℹ packing-list: Amazon linki yok → sayfa noindex, sitemap dışında / no live Amazon links → noindex, not in sitemap');
console.log('\nSonraki adım / next: değişiklikleri GitHub’a gönderin (commit + push).\n');
